animations:
  files:
    - "packages/assets/animations/**"

brand-visuals:
  files:
    - "packages/assets/brand-visuals/**"

fonts:
  files:
    - "packages/assets/fonts/**"

icons:
  files:
    - "packages/assets/icons/**"

illustrations:
  files:
    - "packages/assets/illustrations/**"

tokens:
  files:
    - "packages/assets/tokens/**"

utils:
  files:
    - "packages/assets/utils/**"

components:
  files:
    - "packages/components/**"

docs:
  files:
    - "packages/documentation/**"

tools:
  files:
    - "packages/tools/**"
