name: Publish
run-name: ${{ github.actor }} is running publish

on:
  workflow_dispatch:
  workflow_call:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Setup Environment
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          check-latest: true

      - name: Install Dependencies
        run: yarn

      - name: Build Packages
        run: yarn build

      - name: Set NPM Authorization
        run: yarn config set npmAuthToken ${{ secrets.NPM_TOKEN_CISCO_MD }}

      - name: Deploy NPM Packages
        run: yarn publish:all
